language: php

php:
    - 7
    - 7.1

env:
  - CLICKHOUSE_VERSION=1.1.54159
  - CLICKHOUSE_VERSION=latest

services:
    - docker

install:
    - travis_retry composer self-update && composer --version
    - travis_retry composer install --prefer-dist --no-interaction

before_script:
    - docker run -d -p 127.0.0.1:8123:8123 --name some-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server:$CLICKHOUSE_VERSION

script: ./vendor/bin/phpunit